---
functional:
  - Пользователь должен иметь возможность авторизоваться через e-mail или иной сайт, связанный с данной площадкой. 
  - Пользователь должен иметь возможность настройки личного профиля.
  - Пользователь должен иметь возможность привязки иных соц. сетей.
  - Пользователь должен иметь возможность просматривать свои завершенные игры и статистику.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - требование 5
  - требование 6
